"use client";
import { CheckCircle2, LoaderCircle, MapPin } from "lucide-react";
import { useActionState, useEffect, useState } from "react";
import { saveDefaultAddressAction, type AddressActionState } from "@/app/account/addresses/actions";
import { useLanguage } from "@/components/LanguageProvider";
import { GoogleMapLocationPicker } from "@/components/account/GoogleMapLocationPicker";
type InitialAddress = { fullName: string; phone: string; city: string; addressLine1: string; addressLine2: string; postalCode: string; latitude: number | null; longitude: number | null };
const initialState: AddressActionState = {};
export function AddressForm({ initialAddress, hasSavedAddress, mapsApiKey }: { initialAddress: InitialAddress; hasSavedAddress: boolean; mapsApiKey: string }) {
  const { language } = useLanguage(); const georgian = language === "ka"; const [state, formAction, pending] = useActionState(saveDefaultAddressAction, initialState); const [dirty, setDirty] = useState(false);
  useEffect(() => { if (state.ok) setDirty(false); }, [state.ok, state.savedAt]);
  const saved = (hasSavedAddress || state.ok) && !dirty; const inputClassName = "mt-2 w-full rounded-full border border-hooma-text/10 px-4 py-3 outline-none transition focus:border-hooma-accent";
  return <div className="space-y-6"><div><p className="text-xs uppercase tracking-[0.28em] text-hooma-muted">{georgian ? "მიწოდება" : "Delivery"}</p><h1 className="mt-3 text-4xl font-medium">{georgian ? "ნაგულისხმევი მისამართი" : "Default address"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-hooma-muted">{georgian ? "ეს მონაცემები ავტომატურად შეივსება შეკვეთისას და მომავალში გადაეცემა არჩეულ საკურიერო მომსახურებას." : "These details will be filled in automatically at checkout and later sent to the selected courier service."}</p></div>
    <form action={formAction} onChange={() => setDirty(true)} className="grid gap-5 rounded-[2rem] bg-white/75 p-6 shadow-soft md:grid-cols-2"><input type="hidden" name="language" value={language} />
      <label className="block text-sm font-medium">{georgian ? "მიმღების სახელი და გვარი" : "Recipient full name"}<input name="full_name" required autoComplete="name" defaultValue={initialAddress.fullName} className={inputClassName} /></label><label className="block text-sm font-medium">{georgian ? "მობილურის ნომერი" : "Mobile number"}<input name="phone" required type="tel" autoComplete="tel" defaultValue={initialAddress.phone} className={inputClassName} /></label>
      <label className="block text-sm font-medium">{georgian ? "ქალაქი / ლოკაცია" : "City / location"}<input name="city" required autoComplete="address-level2" defaultValue={initialAddress.city} placeholder={georgian ? "მაგ. თბილისი" : "e.g. Tbilisi"} className={inputClassName} /></label><label className="block text-sm font-medium">{georgian ? "საფოსტო ინდექსი (არასავალდებულო)" : "Postal code (optional)"}<input name="postal_code" autoComplete="postal-code" defaultValue={initialAddress.postalCode} className={inputClassName} /></label>
      <label className="block text-sm font-medium md:col-span-2">{georgian ? "ქუჩა და ნომერი" : "Street and number"}<input name="address_line_1" required autoComplete="address-line1" defaultValue={initialAddress.addressLine1} placeholder={georgian ? "მაგ. ჭავჭავაძის გამზირი 25" : "e.g. 25 Chavchavadze Ave"} className={inputClassName} /></label><label className="block text-sm font-medium md:col-span-2">{georgian ? "სადარბაზო, სართული, ბინა ან დამატებითი მითითება" : "Entrance, floor, apartment, or extra directions"}<input name="address_line_2" autoComplete="address-line2" defaultValue={initialAddress.addressLine2} className={inputClassName} /></label>
      <GoogleMapLocationPicker apiKey={mapsApiKey} language={language} initialLatitude={initialAddress.latitude} initialLongitude={initialAddress.longitude} onLocationChange={() => setDirty(true)} />
      <div className="flex flex-col items-start gap-3 md:col-span-2"><button disabled={pending} className={`inline-flex min-w-52 items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold text-white transition disabled:cursor-wait ${saved ? "bg-emerald-600" : "bg-hooma-text hover:bg-hooma-text/90"}`}>{pending ? <LoaderCircle size={17} className="animate-spin" /> : saved ? <CheckCircle2 size={17} /> : <MapPin size={17} />}{pending ? (georgian ? "ინახება..." : "Saving...") : saved ? (georgian ? "მისამართი შენახულია" : "Address saved") : (georgian ? "მისამართის შენახვა" : "Save address")}</button>{state.message ? <p role="status" aria-live="polite" className={`rounded-xl px-4 py-3 text-sm font-medium ${state.ok ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-800"}`}>{state.message}</p> : null}</div>
    </form></div>;
}
