"use client";
import { Crosshair, ExternalLink, LocateFixed, MapPin } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
type Coordinates = { latitude: number; longitude: number };
type MapsWindow = Window & { google?: any; __hoomaGoogleMapsReady?: () => void };
let mapsPromise: Promise<any> | null = null;
function loadGoogleMaps(apiKey: string, language: "ka" | "en") {
  const mapsWindow = window as MapsWindow; if (mapsWindow.google?.maps) return Promise.resolve(mapsWindow.google.maps); if (mapsPromise) return mapsPromise;
  mapsPromise = new Promise((resolve, reject) => { mapsWindow.__hoomaGoogleMapsReady = () => resolve(mapsWindow.google?.maps); const script = document.createElement("script"); const params = new URLSearchParams({ key: apiKey, loading: "async", callback: "__hoomaGoogleMapsReady", v: "weekly", language, region: "GE", auth_referrer_policy: "origin" }); script.src = `https://maps.googleapis.com/maps/api/js?${params.toString()}`; script.async = true; script.onerror = () => { mapsPromise = null; reject(new Error("Google Maps could not load")); }; document.head.appendChild(script); }); return mapsPromise;
}
function mapsUrl(coordinates: Coordinates | null) { return coordinates ? `https://www.google.com/maps/search/?api=1&query=${coordinates.latitude.toFixed(6)}%2C${coordinates.longitude.toFixed(6)}` : ""; }
export function GoogleMapLocationPicker({ apiKey, language, initialLatitude, initialLongitude, onLocationChange }: { apiKey: string; language: "ka" | "en"; initialLatitude: number | null; initialLongitude: number | null; onLocationChange: () => void }) {
  const georgian = language === "ka"; const mapElementRef = useRef<HTMLDivElement>(null); const mapRef = useRef<any>(null); const interactedRef = useRef(Boolean(initialLatitude !== null && initialLongitude !== null));
  const [coordinates, setCoordinates] = useState<Coordinates | null>(initialLatitude !== null && initialLongitude !== null ? { latitude: initialLatitude, longitude: initialLongitude } : null); const [loading, setLoading] = useState(Boolean(apiKey)); const [error, setError] = useState(""); const [locating, setLocating] = useState(false); const shareUrl = useMemo(() => mapsUrl(coordinates), [coordinates]);
  useEffect(() => { if (!apiKey || !mapElementRef.current) return; let active = true; let listeners: any[] = [];
    loadGoogleMaps(apiKey, language).then(async (maps) => { if (!active || !mapElementRef.current) return; const { Map } = await maps.importLibrary("maps"); if (!active || !mapElementRef.current) return; const center = coordinates ? { lat: coordinates.latitude, lng: coordinates.longitude } : { lat: 41.7151, lng: 44.8271 }; const map = new Map(mapElementRef.current, { center, zoom: coordinates ? 17 : 12, clickableIcons: false, fullscreenControl: true, mapTypeControl: false, streetViewControl: false }); mapRef.current = map;
      const storeCenter = () => { if (!interactedRef.current) return; const selected = map.getCenter(); if (selected) setCoordinates({ latitude: Number(selected.lat().toFixed(7)), longitude: Number(selected.lng().toFixed(7)) }); };
      listeners = [map.addListener("dragstart", () => { interactedRef.current = true; onLocationChange(); }), map.addListener("idle", storeCenter), map.addListener("click", (event: any) => { if (!event.latLng) return; interactedRef.current = true; onLocationChange(); map.panTo(event.latLng); })]; setLoading(false);
    }).catch(() => { if (active) { setLoading(false); setError(georgian ? "Google Maps ვერ ჩაიტვირთა. გადაამოწმე API key და დომენის შეზღუდვა." : "Google Maps could not load. Check the API key and domain restriction."); } });
    return () => { active = false; listeners.forEach((listener) => listener?.remove?.()); mapRef.current = null; };
  }, [apiKey]);
  function useCurrentLocation() { if (!navigator.geolocation) { setError(georgian ? "ამ ბრაუზერს მიმდინარე მდებარეობის მიღება არ შეუძლია." : "This browser cannot access your current location."); return; } setLocating(true); setError(""); navigator.geolocation.getCurrentPosition((position) => { const selected = { latitude: position.coords.latitude, longitude: position.coords.longitude }; interactedRef.current = true; setCoordinates(selected); onLocationChange(); mapRef.current?.setZoom(18); mapRef.current?.panTo({ lat: selected.latitude, lng: selected.longitude }); setLocating(false); }, () => { setLocating(false); setError(georgian ? "ლოკაციის მიღება ვერ მოხერხდა. ბრაუზერში Location წვდომა ჩართე ან რუკა ხელით გადაადგილე." : "Could not get your location. Allow browser location access or move the map manually."); }, { enableHighAccuracy: true, timeout: 12000, maximumAge: 60000 }); }
  return <section className="md:col-span-2"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold">{georgian ? "ზუსტი ლოკაცია Google Maps-ზე" : "Exact Google Maps location"}</p><p className="mt-1 text-xs leading-5 text-hooma-muted">{georgian ? "გადაადგილე რუკა ისე, რომ პინი ზუსტად შესასვლელზე იდგეს, ან გამოიყენე მიმდინარე მდებარეობა." : "Move the map until the pin is exactly at the entrance, or use your current location."}</p></div><button type="button" onClick={useCurrentLocation} disabled={!apiKey || locating} className="inline-flex min-h-10 shrink-0 items-center justify-center gap-2 rounded-full border border-hooma-text/10 bg-white px-4 text-xs font-semibold transition hover:border-hooma-accent disabled:opacity-50"><LocateFixed size={16} />{locating ? (georgian ? "იძებნება..." : "Locating...") : (georgian ? "ჩემი მიმდინარე მდებარეობა" : "Use current location")}</button></div>
    <input type="hidden" name="latitude" value={coordinates?.latitude ?? ""} /><input type="hidden" name="longitude" value={coordinates?.longitude ?? ""} />
    {apiKey ? <div className="relative mt-3 h-[360px] overflow-hidden rounded-[1.5rem] border border-hooma-text/10 bg-hooma-panel"><div ref={mapElementRef} className="h-full w-full" /><div className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-full drop-shadow-lg"><MapPin size={42} className={coordinates ? "fill-hooma-accent text-white" : "fill-hooma-muted text-white"} strokeWidth={1.8} /></div>{loading ? <div className="absolute inset-0 grid place-items-center bg-hooma-panel/90 text-sm font-semibold"><span className="inline-flex items-center gap-2"><Crosshair size={18} />{georgian ? "რუკა იტვირთება..." : "Loading map..."}</span></div> : null}</div> : <div className="mt-3 rounded-[1.5rem] border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950">{georgian ? "რუკის ჩასართავად Vercel-ში დაამატე NEXT_PUBLIC_GOOGLE_MAPS_API_KEY." : "Add NEXT_PUBLIC_GOOGLE_MAPS_API_KEY in Vercel to enable the map."}</div>}
    {error ? <p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p> : null}{coordinates ? <div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><span className="inline-flex items-center gap-2 font-semibold"><MapPin size={16} />{georgian ? "ლოკაცია მონიშნულია" : "Location selected"} · {coordinates.latitude.toFixed(6)}, {coordinates.longitude.toFixed(6)}</span><a href={shareUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-semibold underline underline-offset-2">{georgian ? "Google Maps-ზე გახსნა" : "Open in Google Maps"}<ExternalLink size={13} /></a></div> : <p className="mt-3 text-xs text-hooma-muted">{georgian ? "ზუსტი ლოკაცია ჯერ არ არის მონიშნული." : "An exact location has not been selected yet."}</p>}
  </section>;
}
