import Link from "next/link";
import { catalogCategories } from "@/data/catalog";
import { createClient } from "@/lib/supabase/server";

type ProductListItem = { id: string; name: string; slug: string; category: string; categorySlug: string; subcategory: string; printMinutes: number | null; grams: number | null; price: number | null; production: string; status: string };

export default async function AdminProductsPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string }> }) {
  const params = await searchParams;
  const q = (params.q ?? "").toLocaleLowerCase("ka-GE");
  const category = params.category ?? "all";
  const supabase = (await createClient()) as any;
  const { data: databaseRows } = supabase ? await supabase.from("products").select("id,slug,hooma_name,name_ka,status,production_status,estimated_print_minutes,material_grams,base_price,categories(slug,name_en,name_ka)").order("created_at", { ascending: false }) : { data: [] };

  const databaseProducts: ProductListItem[] = (databaseRows ?? []).map((row: any) => {
    const categoryRow = Array.isArray(row.categories) ? row.categories[0] : row.categories;
    return { id: row.id, name: row.name_ka || row.hooma_name, slug: row.slug, category: categoryRow?.name_ka || categoryRow?.name_en || "—", categorySlug: categoryRow?.slug || "", subcategory: "", printMinutes: row.estimated_print_minutes, grams: row.material_grams, price: row.base_price === null ? null : Number(row.base_price), production: row.production_status, status: row.status };
  });
  const filtered = databaseProducts.filter((product) => `${product.name} ${product.slug}`.toLocaleLowerCase("ka-GE").includes(q) && (category === "all" || product.categorySlug === category));

  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[0.28em] text-hooma-muted">Catalog</p><h1 className="mt-3 text-4xl font-medium">პროდუქტები</h1><p className="mt-2 text-sm text-hooma-muted">{`${databaseProducts.length} პროდუქტი Supabase კატალოგში`}</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/imports" className="rounded-full border border-hooma-text/10 bg-white px-5 py-3 text-sm font-medium">Import Inbox</Link><Link href="/admin/products/new" className="rounded-full bg-hooma-text px-5 py-3 text-sm font-medium text-white">ახალი პროდუქტი</Link></div></div>
    <form className="flex flex-col gap-3 rounded-[1.5rem] bg-white/70 p-4 sm:flex-row"><input name="q" defaultValue={params.q} placeholder="პროდუქტის ძიება" className="min-h-11 flex-1 rounded-full border border-hooma-text/10 px-4 outline-none focus:border-hooma-accent" /><select name="category" defaultValue={category} className="min-h-11 rounded-full border border-hooma-text/10 px-4 outline-none focus:border-hooma-accent"><option value="all">ყველა კატეგორია</option>{catalogCategories.map((item) => <option key={item.slug} value={item.slug}>{item.nameKa}</option>)}</select><button className="rounded-full border border-hooma-text/10 px-5 py-3 text-sm font-medium">ფილტრი</button></form>
    {filtered.length ? <div className="overflow-hidden rounded-[1.5rem] bg-white/75 shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-hooma-panel text-xs uppercase tracking-[0.14em] text-hooma-muted"><tr><th className="px-5 py-4">პროდუქტი</th><th className="px-5 py-4">კატეგორია</th><th className="px-5 py-4">ტექნიკური</th><th className="px-5 py-4">ფასი</th><th className="px-5 py-4">სტატუსი</th></tr></thead><tbody className="divide-y divide-hooma-text/10">{filtered.map((product) => <tr key={product.id}><td className="px-5 py-4"><Link href={`/admin/products/${product.id}`} className="font-medium hover:text-hooma-accent">{product.name}</Link><span className="block text-xs text-hooma-muted">{product.slug}</span></td><td className="px-5 py-4 text-hooma-muted">{product.category}<span className="block text-xs">{product.subcategory}</span></td><td className="px-5 py-4 text-hooma-muted">{product.printMinutes ? `${product.printMinutes} წუთი` : "დრო შესავსებია"}<span className="block text-xs">{product.grams ? `${product.grams} გ` : "წონა შესავსებია"}</span></td><td className="px-5 py-4 font-semibold">{product.price === null ? "—" : `₾${product.price.toFixed(2)}`}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{product.status}</span></td></tr>)}</tbody></table></div></div> : <div className="rounded-[1.5rem] border border-dashed border-hooma-text/15 bg-white/60 px-6 py-14 text-center"><p className="font-semibold">Supabase კატალოგში პროდუქტი ჯერ არ არის</p><p className="mt-2 text-sm text-hooma-muted">დაამატე პირველი პროდუქტი ან გაასუფთავე ძიების ფილტრი.</p></div>}
  </div>;
}
