"use client";

import { useActionState } from "react";
import { CheckCircle2, LockKeyhole } from "lucide-react";
import { createProductDraftFromImportAction } from "@/app/admin/imports/actions";
import type { MaterialCostProfile, PricingProfile } from "@/components/admin/CostSettingsEditor";

type CategoryOption = { id: string; name: string };
const inputClass = "mt-2 w-full rounded-xl border border-hooma-text/10 bg-white px-3 py-2.5 outline-none focus:border-hooma-accent";

export function ImportReviewForm({ importId, defaultName, defaultSlug, defaultDescription, defaultImages, categories, materials, pricing }: { importId: string; defaultName: string; defaultSlug: string; defaultDescription: string; defaultImages: string[]; categories: CategoryOption[]; materials: MaterialCostProfile[]; pricing: PricingProfile }) {
  const [state, action, pending] = useActionState(createProductDraftFromImportAction, {});
  return <form action={action} className="space-y-6"><input type="hidden" name="import_id" value={importId} /><input type="hidden" name="pricing_profile_id" value={pricing.id} />
    <section className="rounded-[1.5rem] bg-white/75 p-6 shadow-soft"><h2 className="text-xl font-semibold">1. Hooma პროდუქტის ინფორმაცია</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">ქართული სახელი<input name="name_ka" required defaultValue={defaultName} className={inputClass} /></label><label className="text-sm font-medium">ინგლისური სახელი<input name="name_en" required defaultValue={defaultName} className={inputClass} /></label><label className="text-sm font-medium">Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={defaultSlug} className={inputClass} /></label><label className="text-sm font-medium">კატეგორია / ქვეკატეგორია<select name="category_id" required className={inputClass}><option value="">აირჩიე</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium sm:col-span-2">აღწერა<textarea name="description" rows={5} maxLength={3000} defaultValue={defaultDescription} className={inputClass} /></label><label className="text-sm font-medium sm:col-span-2">MakerWorld ფოტო-ბმულები<textarea name="image_urls" rows={4} defaultValue={defaultImages.join("\n")} placeholder="თითო ხაზზე ერთი https://makerworld.bblmw.com/... ბმული" className={inputClass} /><span className="mt-2 block text-xs font-normal leading-5 text-hooma-muted">თუ ფოტოები ავტომატურად არ გამოჩნდა, MakerWorld-ზე გახსენი სურათი და მისი მისამართი ჩასვი აქ. მაქსიმუმ 12 ფოტო.</span></label></div></section>

    <section className="rounded-[1.5rem] bg-white/75 p-6 shadow-soft"><h2 className="text-xl font-semibold">2. ტექნიკური პროფილი და ფასი</h2><p className="mt-2 text-sm text-hooma-muted">ეს მონაცემები უნდა დაემთხვეს Bambu Studio/3MF პროფილს. მათზე დაყრდნობით ითვლება გასაყიდი ფასი.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-medium">მასალა<select name="material_profile_id" required className={inputClass}>{materials.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">წონა, გრამი<input name="material_grams" type="number" min="0.01" step="0.01" required className={inputClass} /></label><label className="text-sm font-medium">ბეჭდვის დრო, წუთი<input name="print_minutes" type="number" min="1" required className={inputClass} /></label><label className="text-sm font-medium">ფირფიტების რაოდენობა<input name="plate_count" type="number" min="1" max="100" defaultValue="1" required className={inputClass} /></label><label className="text-sm font-medium">X ზომა, მმ<input name="dimension_x" type="number" min="0.01" step="0.01" required className={inputClass} /></label><label className="text-sm font-medium">Y ზომა, მმ<input name="dimension_y" type="number" min="0.01" step="0.01" required className={inputClass} /></label><label className="text-sm font-medium">Z ზომა, მმ<input name="dimension_z" type="number" min="0.01" step="0.01" required className={inputClass} /></label><label className="text-sm font-medium">მოგების მარჟა, %<input name="margin_percent" type="number" min="0" max="99.99" step="0.01" defaultValue={pricing.default_margin_percent} required className={inputClass} /></label></div></section>

    <section className="rounded-[1.5rem] border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-2"><LockKeyhole size={18} /><h2 className="text-xl font-semibold">3. ლიცენზია და ფოტოების უფლება</h2></div><p className="mt-2 text-sm leading-6 text-amber-900/75">Checkbox მონიშნე მხოლოდ მაშინ, როდესაც წყაროს ლიცენზია ან ავტორის წერილობითი ნებართვა ნამდვილად შეამოწმე. დაუდასტურებელი Draft ვერ გამოქვეყნდება.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">ლიცენზიის სახელი<input name="license_name" placeholder="მაგ. CC BY 4.0 / Creator permission" className={inputClass} /></label><label className="text-sm font-medium">ლიცენზიის ან მტკიცებულების URL<input name="license_url" type="url" className={inputClass} /></label><label className="flex items-start gap-3 rounded-xl bg-white/70 p-4 text-sm"><input name="commercial_use_allowed" type="checkbox" className="mt-1" /><span><strong className="block">კომერციული გამოყენება ნებადართულია</strong><span className="mt-1 block text-xs text-hooma-muted">დაბეჭდილი პროდუქტის გაყიდვის უფლება დადასტურებულია.</span></span></label><label className="flex items-start gap-3 rounded-xl bg-white/70 p-4 text-sm"><input name="media_use_allowed" type="checkbox" className="mt-1" /><span><strong className="block">ფოტოების გამოყენება ნებადართულია</strong><span className="mt-1 block text-xs text-hooma-muted">წყაროს სურათების Hooma-ზე ჩვენების უფლება დადასტურებულია.</span></span></label></div></section>

    {state.message ? <div className={`rounded-xl p-4 text-sm ${state.ok ? "bg-emerald-50 text-emerald-900" : "bg-red-50 text-red-800"}`}>{state.ok ? <CheckCircle2 size={16} className="mr-2 inline" /> : null}{state.message}{state.productId ? <span className="ml-2 font-semibold">ID: {state.productId.slice(0, 8)}</span> : null}</div> : null}
    <button disabled={pending || !materials.length || !categories.length} className="w-full rounded-xl bg-hooma-text px-6 py-4 font-semibold text-white disabled:opacity-45">{pending ? "Draft იქმნება..." : "პროდუქტის Draft-ის შექმნა"}</button>
  </form>;
}
